const names = {
	welcome: '/',
	home: '/home/',
	search: '/home/search/',
	explore: '/home/explore/',
	foodBasket: '/home/foodBasket/',
	profile: '/home/profile/',
	recipe: '/recipe/',
	listRecipes: '/recipes/',
	signUp: '/signUp/',
	signIn: '/signIn/',
	forgetPassword: '/forgetPassword/',
	forgetPasswordValidate: '/forgetPassword/validate/',
	newPassword: '/forgetPassword/newPassword/',
	foodBasketAdd: '/foodBasket/add/',
	aboutUs: '/profile/aboutUs/',
	contactUs: '/profile/contactUs/',
	editProfile: '/profile/edit/',
	language: '/profile/language/',
	legalInformation: '/profile/legalInformation/',
	termsAndConditions: '/profile/legalInformation/termsAndConditions/',
	privacyPolicy: '/profile/legalInformation/privacyPolicy/',
	cookiesPolicy: '/profile/legalInformation/cookiesPolicy/',
	preferences: '/profile/preferences/',
	myObjectives: '/profile/preferences/myObjectives/',
	cookingLevel: '/profile/preferences/cookingLevel/',
	diet: '/profile/preferences/diet/',
	allergies: '/profile/preferences/allergies/',
	dislikeIngredient: '/profile/preferences/dislikeIngredient/',
	comensals: '/profile/preferences/comensals/',
	settings: '/profile/settings/',
	measurementUnits: '/profile/measurementUnits/',
	theme: '/profile/theme/',
};

export default names;
